sonar.projectKey=jenkins-sonar
sonar.projectName=jenkins-sonar
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.login=squ_ac3542af1dad1eb4b6413005e311aee95e11a6af
